apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-cron2
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job2
            image: busybox
            command: ["sh", "-c", "date; echo Hello"]
          restartPolicy: OnFailure

